# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.comassets/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

# Permalinks
permalink: pretty

# Setup
title: AAZ Development Tool
email: kairu@microsoft.com
description: >- # this means to ignore newlines until "baseurl:"
  AAZ Development Tool is designed to generate atomic Azure CLI commands from OpenAPI specifications.

baseurl: "/aaz-dev-tools" # the subpath of your site, e.g. /blog
url: "https://azure.github.io" # the base hostname & protocol for your site, e.g. http://example.com

github:
  repo: https://github.com/Azure/aaz-dev-tools

pypi: https://pypi.org/project/aaz-dev/

# TODO: get version number from github
version: v1.3.1

# Build settings
theme: minima
plugins:
  - jekyll-feed
